### ISSUE TITLE
[IE11-QA] favorites can have duplicates

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1254] opened 2019-06-05 14:50 UTC
I have multiple folders in different locatins in the tree named 'deep' and multiple files in different locations named 'diver.txt' -- makeing multiple of them favorites looks like this
![grafik](https://user-images.githubusercontent.com/1108546/58965980-be1c5600-87b1-11e9-89f2-a2f2c22dd90b.png)

Users cannot tell which is which. There should be an indicator showing the full path. E.g. mouse over tooltip?

**Comment by individual-it** [comment] 2019-06-06 03:16
duplicate of #1194 ?

**Closed** 2019-06-07 06:43 UTC
