### ISSUE TITLE
trashbin unusable and ugly on small screens

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1890] opened 2019-09-03 05:13 UTC
### Steps to reproduce
1. use the trashbin on a small screen e.g. 375 widht

### Expected behaviour
file name should be visible
no scrolling needed
no overlapping text

### Actual behaviour
![image](https://user-images.githubusercontent.com/2425577/64143667-cc215780-ce30-11e9-80d3-9a1007c7f1cf.png)

**Comment by PVince81** [comment] 2019-09-24 14:01
duplicate of https://github.com/owncloud/phoenix/issues/1760

**Closed by PVince81** 2019-09-24 14:01 UTC
Labels: bug, junior job, p3-medium
