### ISSUE TITLE
OIDC unknown user error message should stay visible

### ISSUE THREAD

**Issue by hodyroff** [owncloud/phoenix#2020] opened 2019-09-19 16:53 UTC
After OIDC IDP coming with an unknown user we display the error message for such users for a moment, but don't stay on the page.

**Comment by LukasHirt** [comment] 2019-09-22 22:30
Seems that we are triggering the logout redirect after there is an error during the authorization, including access denied. Is this the desired behaviour? Should this be disabled only in this case? I don't really see a reason why the user would be logged out from whole OIDC when he encountered an error in Phoenix.

**Comment by hodyroff** [comment] 2019-09-23 06:23
IMO the desired behavior would be the error message page with a button to be directed to the login process again ... so that the user name can be changed if needed. Before such login button is pressed, the error message is static.

**Comment by PVince81** [comment] 2019-09-23 08:35
assigned to @DeepDiver1975 as discussed with him as it requires some proper setup to reproduce this

**Comment by DeepDiver1975** [comment] 2019-09-25 09:17
> so that the user name can be changed if needed

If we don't trigger the logout on the idp - users have not the opportunity to change their user id.

Nevertheless - users should know how to logout from their idp - this is not within our responsibility.

I agree that a hard logout is wrong....

**Comment by DeepDiver1975** [comment] 2019-09-25 09:35
Another interesting question:
As soon as the access token did expire: logout is triggered as well ... this seems to be wrong ..

**Closed** 2019-09-25 12:21 UTC
Labels: bug, p1-urgent
