### ISSUE TITLE
collaborator with only change permission is displayed as Editor

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1897] opened 2019-09-05 05:55 UTC
### Steps to reproduce
1. Share a folder with user and assign collaborator permission ```change```
![1](https://user-images.githubusercontent.com/34328907/64315645-58b74b80-cfd2-11e9-91a6-94675418190a.png)

2. Now the user/collaborator is dispalyed as Editor
![2](https://user-images.githubusercontent.com/34328907/64315660-653ba400-cfd2-11e9-93d4-af29914e8fa9.png)

### Expected behaviour
Collaborator with only ```change``` permission must be displayed as ```Custom Role```

### Actual behaviour
Collaborator with only ```change``` permission is displayed as ```Editor```

**Comment by PVince81** [comment] 2019-09-13 07:53
> The problem is that with the custom role you can get the same set of perms as a role has which will lead to showing that role after saving instead of custom.

This is fine. If the user selects a set of perms that match a role, then we should just show that role after reloading.

The problem is mostly about having multiple sets of perms that map to the same role name. So the role name itself has a confusing meaning. The latter might be a side-effect of the bug that we did not distinguish between file and folder perms.

**Comment by PVince81** [comment] 2019-09-27 08:12
increasing to p2 as this is a broken feature

**Comment by PVince81** [comment] 2019-10-23 11:38
As discussed with @LukasHirt, we need to first solve the technical debt with the following items:
- [ ] always use hash arrays with permission name as key and boolean as value
- [ ] in actions always convert back and forth between bitmask perms and array perms
- [ ] optional: also read share attributes
- [ ] define hard-coded roles, try to use https://github.com/owncloud/core/pull/36024#issue-306903684 as inspiration as we might one day read from that
- [ ] on what level to put resourceType ?
- [ ] have a field roleId in the state. if not populated it means "advanced" and UI needs to display checkboxes

This would also provide the resource type separation which will make it possible to fix the bug in an elegant way.

**Comment by PVince81** [comment] 2019-11-25 13:48
Should be fixed already with https://github.com/owncloud/phoenix/pull/2373

**Closed by PVince81** 2019-11-25 13:48 UTC
Labels: Effort: 0.5d, bug, feature:collaborators, p2-high
