### ISSUE TITLE
Scroll not working on files page in firefox 

### ISSUE THREAD

**Issue by jasson99** [owncloud/phoenix#2436] opened 2019-11-12 03:41 UTC
### Steps to reproduce
1.Build the latest phoenix
2.Open phoenix on firefox
3.Go to files page and then try to scroll.Make sure there are enough files to scroll

### Expected behaviour
Scrolling should work

### Actual behaviour
Scrolling does not work

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySql

**PHP version:** 7.2.24

### Client configuration
**Browser:** Firefox 70.0.1

**Operating system:** Ubuntu 18.04

#### Browser log
```
There has been a problem with your fetch operation:  Network response was not ok. core.bundle.js:105:24059
```

**Comment by dpakach** [comment] 2019-11-12 03:48
Seems to have introduced by commit 9059ea2782349293117342ba8093e1655603dec4

**Comment by PVince81** [comment] 2019-11-12 08:17
@Julian1998 please fix this regression before others

**Comment by LukasHirt** [comment] 2019-11-12 08:55
Let's maybe wait until this PR is merged #2280 ? Since it's touching this area

**Comment by Julian1998** [comment] 2019-11-15 15:55
@LukasHirt I guess the problem is too urgent and as the fix seems to be that easy, fix first.

**Comment by jasson99** [comment] 2019-11-19 05:39
This issue has been fixed by this PR - https://github.com/owncloud/phoenix/pull/2475.I just tried and it worked.Waiting for this fix to be merged

**Closed** 2019-11-19 08:50 UTC
Labels: bug, p1-urgent, regression
