### ISSUE TITLE
do not add border to filelist when clicking it

### ISSUE THREAD

**Issue by butonic** [owncloud/phoenix#3747] opened 2020-07-08 07:23 UTC
### Steps to reproduce
1. click in the white area below the existing files

### Expected behaviour
nothing should visually change

### Actual behaviour
The file list gets a border.

**Comment by PVince81** [comment] 2020-07-08 07:27
related: https://github.com/owncloud/phoenix/issues/3046

**Comment by kulmann** [comment] 2020-07-08 13:12
duplicate of https://github.com/owncloud/phoenix/issues/3551

**Comment by kulmann** [comment] 2020-07-08 13:12
fyi, PR is already here: https://github.com/owncloud/phoenix/pull/3752

**Closed** 2020-07-08 13:12 UTC
Labels: bug, junior job
