### ISSUE TITLE
[QA] Whitespace in a filename causes entry field to jump up and down

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#2087] opened 2019-09-27 14:41 UTC
See also: #1969 (trailing dot have same effect as trailing whitespace)

User creates a new folder. The name suggestion is 'New folder'. When the user backspaces and edits the name, the  text entry field changes position while typing, whenever a whitespace is the last character typed, due to an error message blinking in red above.

![image](https://user-images.githubusercontent.com/1108546/65777938-4188fb00-e145-11e9-9573-fa30cb35f041.png)

After erasing 'folder' but keeping the ' ':
![image](https://user-images.githubusercontent.com/1108546/65778069-7eed8880-e145-11e9-96ee-f18552301c08.png)

Expected behaviour:
* Do not move the entry field around while typing or erasing.

Suggested implementations:
* Have the space for the error message always in the dialog.
* Have the error message delayed so that it can blink only very slow.
* Do not show any error messages (to be in sync with reported #1969 behavior -- Not prefered)

Note that this jumping will become much worse, if #1969 would get fixed.

**Comment by PVince81** [comment] 2019-09-30 07:27
duplicate of https://github.com/owncloud/phoenix/issues/1906

**Closed by PVince81** 2019-09-30 07:27 UTC
