### ISSUE TITLE
Error shown trying to restore 2 files same named at the same time

### ISSUE THREAD

**Issue by davitol** [owncloud/phoenix#3477] opened 2020-05-19 08:37 UTC
### Steps to reproduce

1. Create a file e.g.  `file.txt`
2. Delete `file.txt`
3. Create `file.txt`
4. Delete `file.txt`
5. Go to trashbin section, select both files and try to restore them

### Expected behaviour

Both files should be restored (maybe one named as restored)

### Actual behaviour

One of the restores fails.

### Server configuration
phoenix.owncloud.com

### Client configuration

**Browser:** Safari 13.1 (15609.1.20.111.8)

**Operating system:** macOS Catalina 10.15.4

### Screenshot

Phoenix behavior

<img width="1270" alt="Screenshot 2020-05-19 at 08 31 03" src="https://user-images.githubusercontent.com/10596560/82304080-2280f700-99bc-11ea-986c-d37b6bcb5dd3.png">

oC10 behavior

![Screenshot 2020-05-19 at 10 23 07](https://user-images.githubusercontent.com/10596560/82304155-3c223e80-99bc-11ea-98c4-532c6d8e70bc.png)

**Comment by davitol** [comment] 2020-05-19 08:37
If this is not the right repo, please comment and I will open the ticket in other repo

**Comment by PVince81** [comment] 2020-05-19 08:44
duplicate of https://github.com/owncloud/phoenix/issues/1730

**Closed by PVince81** 2020-05-19 08:44 UTC
Labels: bug
