### ISSUE TITLE
Shared with me tab does not show up shares

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#3017] opened 2020-02-12 11:16 UTC
Phoenix version 0.3.0 against Reva

Clicking "Shared with me" gives:

```
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK"},"data":[]}}
```

but the UI will show "My files" instead of an empty list and in the console I see this:

```
[Vue warn]: Missing required prop: "label"

found in

---> <OcCheckbox>
       <OcDrop>
         <FileFilterMenu>
           <OcGrid>
             <FilesAppBar>
               <Anonymous>
                 <Phoenix> at src/Phoenix.vue
                   <Root> 3 vue.js:634
[Vue warn]: Missing required prop: "label"

found in

---> <OcSearchBar>
       <OcDrop>
         <FileFilterMenu>
           <OcGrid>
             <FilesAppBar>
               <Anonymous>
                 <Phoenix> at src/Phoenix.vue
                   <Root> vue.js:634
    VueJS 7
    _init vue-gettext.js:787
    VueJS 49
    notify es.promise.js:114
    flush microtask.js:26
Unhandled promise rejection SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" host-report-errors.js:6
Unhandled promise rejection SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" host-report-errors.js:6

```

**Comment by PVince81** [comment] 2020-02-12 14:41
Duplicate of https://github.com/owncloud/phoenix/issues/2150

**Closed by PVince81** 2020-02-12 14:41 UTC
